version: '3'

volumes:
  db_data:
    driver: local
  
networks:
  for_do_network:
    driver: bridge
    name: for_do_network

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    
  frontend:
    build: ./front-end/for_do_frontend
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./front-end/for_do_frontend:/for_do_frontend
    ports:
      - "3000:3000"
    tty: true
    